# 路径
server:
  context-path: /
  port: 8081

spring:
  profiles:
    active: test
# thymeleaf
  thymeleaf:
   cache: false
   prefix: classpath:/templates/
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: HTML5
